{% set name = "webexteamssdk" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbc7672f381b26fb22d0d03f87d131a2fa1e7d54c2f37f2e4cd28d725b8b5dfb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - future
    - pyjwt
    - python
    - requests >=2.4.2
    - requests-toolbelt

test:
  imports:
    - webexteamssdk
    - webexteamssdk.api

about:
  home: https://github.com/CiscoDevNet/webexteamssdk
  summary: Community-developed Python SDK for the Webex Teams APIs
  license: MIT
  license_file: webexteamssdk/models/mixins/license.py

extra:
  recipe-maintainers:
    - synapticarbors
