{% set name = "webexteamssdk" %}
{% set version = "1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4cc8e7d000d5cf3e25913966bfb2af6d023b1dcc51b75e1cea19e89ebc3f1d00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - future
    - pyjwt
    - python >={{ python_min }}
    - requests >=2.4.2
    - requests-toolbelt

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - webexteamssdk
    - webexteamssdk.api
  commands:
    - pip check

about:
  home: https://github.com/CiscoDevNet/webexteamssdk
  summary: Community-developed Python SDK for the Webex Teams APIs
  license: MIT
  license_file: webexteamssdk/models/mixins/license.py

extra:
  recipe-maintainers:
    - synapticarbors
