{% set name = "webexteamssdk" %}
{% set version = "1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 980f268d89187d1a157dfbadcb626fce849080a31550e549cfe838f0203b3a3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - future
    - pyjwt
    - python
    - requests >=2.4.2
    - requests-toolbelt

test:
  imports:
    - webexteamssdk
    - webexteamssdk.api

about:
  home: https://github.com/CiscoDevNet/webexteamssdk
  summary: Community-developed Python SDK for the Webex Teams APIs
  license: MIT
  license_file: webexteamssdk/models/mixins/license.py

extra:
  recipe-maintainers:
    - synapticarbors
